
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pv-claim-demo
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi